apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
   name: flask-argocd
spec:
  destination:
    name: ''
    namespace: flask-argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: k8s/
    repoURL: 'https://@github.com:Crypto-TII/flask-argocd.git'
    targetRevision: HEAD
    directory:
       recurse: true
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2