name: CI

on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Build and Pushing the Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      run: |
        # Build docker container
        git_hash=$(git rev-parse --short "$GITHUB_SHA")
        docker build -t ${DOCKERHUB_USERNAME}/flask-argocd:${GITHUB_REF##*/}-$git_hash .
        echo "Pushing image..."
        docker push ${DOCKERHUB_USERNAME}/flask-argocd:${GITHUB_REF##*/}-$git_hash
      env:
        DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}

    - name: Update Image Version in the yaml
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: 'k8s/helm/values.yaml'
        propertyPath: 'image.tag'
        value: ${GITHUB_REF##*/}-$git_hash
        masterBranchName: 'master'
        branch: 'master'
        message: 'Update image version from github-actions'