name: CI

on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Build and Pushing the Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}

    - name: Build, tag, and push image to dockerhub
      id: build-image
      run: |
        # Build docker container
        git_hash=$(git rev-parse --short "$GITHUB_SHA")
        docker build -t ${DOCKER_USERNAME}/flask-argocd:${GITHUB_REF##*/}-$git_hash -f docker/Dockerfile .
        echo "Pushing image..."
        docker push ${DOCKER_USERNAME}/flask-argocd:${GITHUB_REF##*/}-$git_hash
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}

    - name: Update Image Version in the related HelmChart values.yaml
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: 'k8s/helm/values.yaml'
        propertyPath: 'tag'
        value: ${GITHUB_REF##*/}-$git_hash
        branch: master
        message: 'Update Image Version to ${GITHUB_REF##*/}-$git_hash' 